version: '3.8'

services:

  mr-frontend:
    restart: unless-stopped
    # depends_on:
    #     - backend
    # links:
    #     - "nginx-dev:api.${DOMAIN}"
    build:
        context: .
        dockerfile: dev.Dockerfile
    env_file:
      - ./.env
    environment:
        BASE_API_URL: http://api.dev.${DOMAIN}
    volumes:
        - node_modules:/app/node_modules
        - .:/app

volumes:
    node_modules: